// Constants and configuration values
const DEFAULT_MAX_RESULT_SIZE_GB = 30;
// NZBDAV listing backend. `auto` prefers a native InfiniDysk JSON API and
// falls back to generic WebDAV; `generic` disables the native API entirely.
const NZBDAV_BACKEND_VALUES = Object.freeze(['auto', 'generic', 'infinidysk']);
const DEFAULT_NZBDAV_BACKEND = 'auto';

const ADMIN_CONFIG_KEYS = [
  'ADDON_BASE_URL',
  'ADDON_SHARED_SECRET',
  'INDEXER_MANAGER',
  'INDEXER_MANAGER_URL',
  'INDEXER_MANAGER_API_KEY',
  'INDEXER_MANAGER_INDEXERS',
  'INDEXER_MANAGER_STRICT_ID_MATCH',
  'NZBDAV_URL',
  'NZBDAV_BACKEND',
  'NZBDAV_API_KEY',
  'INFINIDYSK_FRONTEND_API_KEY',
  'NZBDAV_WEBDAV_URL',
  'NZBDAV_WEBDAV_USER',
  'NZBDAV_WEBDAV_PASS',
  'NZBDAV_CATEGORY',
  'NZBDAV_CATEGORY_MOVIES',
  'NZBDAV_CATEGORY_SERIES',
  'NZBDAV_CATEGORY_DEFAULT',
  'NZBDAV_HISTORY_CATALOG_LIMIT',
  'NZBDAV_HISTORY_FETCH_LIMIT',
  'NZBDAV_CACHE_TTL_MINUTES',
  'NZB_SORT_MODE',
  'NZB_RANKED_RULES',
  'NZB_PREFERRED_LANGUAGE',
  'NZB_MAX_RESULT_SIZE_GB',
  'NZB_ALLOWED_RESOLUTIONS',
  'NZB_RESOLUTION_LIMIT_PER_QUALITY',
  'NZB_RELEASE_EXCLUSIONS',
  'NZB_TRIAGE_ENABLED',
  'NZB_TRIAGE_MAX_CANDIDATES',
  'NZB_TRIAGE_NNTP_HOST',
  'NZB_TRIAGE_NNTP_PORT',
  'NZB_TRIAGE_NNTP_USER',
  'NZB_TRIAGE_NNTP_PASS',
  'NZB_TRIAGE_NNTP_USE_TLS',
  'NZB_TRIAGE_NNTP_TIMEOUT',
  'NZB_TRIAGE_NNTP_MAX_CONNECTIONS',
  'NZB_TRIAGE_REUSE_POOL',
  'NZB_TRIAGE_NNTP_KEEP_ALIVE_MS',
  'NZB_TRIAGE_PREFETCH_FIRST_VERIFIED',
  'NZB_TRIAGE_ARCHIVE_DIRS',
  'NZB_TRIAGE_MAX_PARALLEL',
  'NZB_TRIAGE_STAT_SAMPLE_COUNT',
  'NZB_TRIAGE_ARCHIVE_SAMPLE_COUNT',
  'NZB_TRIAGE_TIMEOUT_MS',
  'STREAM_CACHE_TTL_MINUTES',
  'STREAM_CACHE_MAX_SIZE_MB',
  'VERIFIED_NZB_CACHE_TTL_MINUTES',
  'VERIFIED_NZB_CACHE_MAX_SIZE_MB',
  'SPECIAL_API_ENABLED',
  'SPECIAL_API_PROVIDER',
  'SPECIAL_API_KEY',
  'TMDB_ENABLED',
  'TMDB_API_KEY',
  'TMDB_SEARCH_LANGUAGES',
  'TVDB_ENABLED',
  'TVDB_API_KEY',
];

const VIDEO_EXTENSIONS = new Set([
  '.mp4', '.mkv', '.avi', '.mov', '.wmv', '.flv',
  '.webm', '.m4v', '.mpg', '.mpeg', '.3gp', '.ts'
]);

module.exports = {
  DEFAULT_MAX_RESULT_SIZE_GB,
  NZBDAV_BACKEND_VALUES,
  DEFAULT_NZBDAV_BACKEND,
  ADMIN_CONFIG_KEYS,
  VIDEO_EXTENSIONS,
};
